package com.example.a100456794.login2;

import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class ContactUsFragment extends Fragment {

    private static final String TAG = ContactUsFragment.class.getSimpleName();

    private EditText name;
    private EditText surname;
    private TextView option1;  // newly opened
    private TextView option2;  // closed
    private TextView option3;  // other
    private EditText message;
    private Button send;
    private String reasonOfEmail;
    private String emailSubject = "CBDFinder";

    private String receiverEmail = "cbdfindercon@gmail.com";

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_contact_us, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        name = view.findViewById(R.id.email_name);
        surname = view.findViewById(R.id.email_surname);
        option1 = view.findViewById(R.id.email_option_1);
        option2 = view.findViewById(R.id.email_option_2);
        option3 = view.findViewById(R.id.email_option_3);
        message = view.findViewById(R.id.email_feedback);
        send = view.findViewById(R.id.email_send);

        option1.setBackgroundColor(Color.WHITE);
        option2.setBackgroundColor(Color.alpha(0));
        option3.setBackgroundColor(Color.alpha(0));

        option1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                optionButtonClicked(v);
            }
        });
        option2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                optionButtonClicked(v);
            }
        });
        option3.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                optionButtonClicked(v);
            }
        });
        send.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                sendButtonClicked(v);
            }
        });
    }

    public void optionButtonClicked(View view) {
        switch (view.getId()) {
            case R.id.email_option_1:
                reasonOfEmail = "Newly opened";
                option1.setBackgroundColor(Color.WHITE);
                option2.setBackgroundColor(Color.alpha(0));
                option3.setBackgroundColor(Color.alpha(0));
                return;

            case R.id.email_option_2:
                reasonOfEmail = "Closed";
                option1.setBackgroundColor(Color.alpha(0));
                option2.setBackgroundColor(Color.WHITE);
                option3.setBackgroundColor(Color.alpha(0));
                return;

            default:
                reasonOfEmail = "Other";
                option1.setBackgroundColor(Color.alpha(0));
                option2.setBackgroundColor(Color.alpha(0));
                option3.setBackgroundColor(Color.WHITE);
                return;
        }

    }

    public void sendButtonClicked(View view) {
        String nameString = name.getText() + "";
        String surnameString = surname.getText() + "";
        String messageString = message.getText() + "";
        if (nameString == "" || surnameString == "" || messageString == "") {
            Toast.makeText(getActivity(), "Please, fill in all text fields.", Toast.LENGTH_LONG).show();
            return;
        }

        Log.d(TAG, "sendButtonClicked: " + nameString + surnameString + messageString);

        String email = "User: " + nameString + " " + surnameString +
                "\nCategory: " + reasonOfEmail +
                "\nMesssage: " + messageString +
                "\n\nThis email is generated by CBDFinder Android app.";

        Intent i = new Intent(Intent.ACTION_SEND);
        i.setType("message/rfc822");
        i.putExtra(Intent.EXTRA_EMAIL, new String[]{receiverEmail});
        i.putExtra(Intent.EXTRA_SUBJECT, emailSubject);
        i.putExtra(Intent.EXTRA_TEXT, email);
        try {
            startActivity(Intent.createChooser(i, "Send email..."));
        } catch (android.content.ActivityNotFoundException ex) {
            Toast.makeText(getActivity(), "There are no email apps installed on this device", Toast.LENGTH_LONG).show();
        }
    }
}
